### ISSUE TITLE
Can't start SNT

### ISSUE THREAD

**Issue by KoenKole** [morphonets/SNT#192]
**Describe the bug**
SNT won't start. The image file opens but after that the startup gets stuck.
Maybe I need some additional plugin/package? Thanks for your help!

**To Reproduce**

1. Go to 'Plugins > Neuroanatomy'
2. Click on 'SNT...'
3. Browse to file to trace, putting all the settings (tracing file is left blank as I'm starting a new one)
4. Click "OK"
5. Image file opens, along with XZ and ZY navigation
6. Error appears (see full error below); nothing else happens

**Expected behavior**
Startup of SNT

Below is the error message I get:
```
(Fiji Is Just) ImageJ 2.14.0/1.54f; Java 1.8.0_322 [64-bit]; Windows 10 10.0; 740MB of 11653MB (6%)
 
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Module threw exception
	at net.imagej.legacy.LegacyService.runLegacyCompatibleCommand(LegacyService.java:308)
	at net.imagej.legacy.DefaultLegacyHooks.interceptRunPlugIn(DefaultLegacyHooks.java:166)
	at ij.IJ.runPlugIn(IJ.java)
	at ij.Executer.runCommand(Executer.java:152)
	at ij.Executer.run(Executer.java:70)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Module threw exception
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at net.imagej.legacy.LegacyService.runLegacyCompatibleCommand(LegacyService.java:304)
	... 5 more
Caused by: java.lang.RuntimeException: Module threw exception
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:128)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:64)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:247)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	... 1 more
Caused by: java.lang.NullPointerException
	at sc.fiji.snt.SNT.startUI(SNT.java:649)
	at sc.fiji.snt.gui.cmds.SNTLoaderCmd.initPlugin(SNTLoaderCmd.java:334)
	at sc.fiji.snt.gui.cmds.SNTLoaderCmd.run(SNTLoaderCmd.java:324)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:165)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:125)
	... 6 more
```

**Comment by carshadi** [comment]
Hi @KoenKole ,

Sorry you are having problems starting the program. I haven't had luck reproducing this on the same setup as yours, so I have a couple questions which will help narrow down the cause.
1) If you open SNT without an image, do things start normally?
2) How large is your image (in MB), and what is the file format?
3) Are you using the latest SNT version v`4.2.1`?
4) Does the main SNT control panel open and then freeze? Or does it only display the 3-pane image windows with no other components (Path Manager, etc), and things remain responsive?

**Comment by tferr** [comment]
Another question is:
5. What Java are you using? The default one that is bundled inside the Fiji.app folder, or a system-wide installation? You can get this info by running Help -> About SNT... and clicking on the java version
![image](https://github.com/morphonets/SNT/assets/2439948/ff6c8586-52c3-49a6-a7b5-1dd2f9db4782)

**Comment by KoenKole** [comment]
> Hi @KoenKole ,
> 
> Sorry you are having problems starting the program. I haven't had luck reproducing this on the same setup as yours, so I have a couple questions which will help narrow down the cause.
> 
> 1. If you open SNT without an image, do things start normally?
> 2. How large is your image (in MB), and what is the file format?
> 3. Are you using the latest SNT version v`4.2.1`?
> 4. Does the main SNT control panel open and then freeze? Or does it only display the 3-pane image windows with no other components (Path Manager, etc), and things remain responsive?

Thank you and tferr for your reply (and apologies for the delay in mine)!
It turned out point 3 was the most relevant: I was unaware that I was trying to use an outdated version of SNT. I updated it to v4.2.1 and now it seems to work as it should.

Many thanks to both of you for your help!

Best,

Koen
