### ISSUE TITLE
Measure_Multiple_Files_(With_Options).groovy

### ISSUE THREAD

**Issue by carshadi** [morphonets/SNT#29]
Error when running AnalyzerCmd from the script editor. The error does not occur when using the ```Measure...``` command in the GUI.
```
[ERROR] Module threw exception
java.lang.ClassCastException: ij.ImagePlus cannot be cast to sc.fiji.snt.Tree
	at sc.fiji.snt.plugin.AnalyzerCmd.measure(AnalyzerCmd.java:289)
	at sc.fiji.snt.plugin.AnalyzerCmd.run(AnalyzerCmd.java:257)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:165)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:124)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:63)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:225)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by tferr** [comment]
This is funky. It looks as if something in the @ script parameters is passing on images to the command. Maybe if one uses `#@CommandService cmd` directly as opposed to `ij.command()` the issue would go away? @carshadi, do you mind trying?

**Comment by carshadi** [comment]
Doing ```cmd.run(AnalyzerCmd.class, true, null)``` produces the same exception for me. One thing I noticed is this extra parameter which is not present in the GUI cmd, perhaps it is related to this?. 
![image](https://user-images.githubusercontent.com/44130022/86292936-a59e8b00-bbbf-11ea-96bb-94d507d0f7ce.png)

**Comment by tferr** [comment]
I see. It only appears when you have at least an image open. I can reproduce it now, after opening an image. I still think it is a bug somewhere in scijava, but does it go away for you if you do?
```groovy
ij.command().run(AnalyzerCmd.class, true, ['trees':null])
```
(we are basically filling the input `trees` with a dummy value, so that scijava does not try to populate it automatically

**Comment by carshadi** [comment]
The issue goes away if I use your snippet

**Comment by tferr** [comment]
I applied the above solution in AnalyzerCmd itself. Closing this. Feel free to reopen if the issue persists
