### ISSUE TITLE
UI reference to Viewer3D not nullified upon viewer disposal

### ISSUE THREAD

**Issue by carshadi** [morphonets/SNT#33]
Call _Analyze_ > _Color coding..._ in the Path Manager and display the Rec. viewer color map. Then quit Viewer3D. Then perform the color coding again:

```
Exception in thread "Thread-13" java.lang.NullPointerException
	at sc.fiji.snt.viewer.Viewer3D.syncPathManagerList(Viewer3D.java:1392)
	at sc.fiji.snt.SNT.lambda$updateNonTracingViewers$1(SNT.java:2378)
	at java.lang.Thread.run(Thread.java:748)
[INFO] [SNT] Color Coding Trees (Cable length) using Ice.lut
[INFO] [SNT] Creating 2D plots...
[ERROR] Module threw exception
java.lang.NullPointerException
	at org.jzy3d.chart.Chart.add(Chart.java:304)
	at sc.fiji.snt.viewer.Viewer3D.addColorBarLegend(Viewer3D.java:976)
	at sc.fiji.snt.plugin.MultiTreeMapperCmd.run(MultiTreeMapperCmd.java:131)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:165)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:124)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:63)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:225)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
The reference to the viewer instance is not cleared from the UI component when closing the viewer.
Relevant code snippet:
https://github.com/morphonets/SNT/blob/a44680b675182376be0c65129eb6fbdec0e213c4/src/main/java/sc/fiji/snt/SNTUtils.java#L100-L103

workaround:
```
	public static synchronized void removeViewer(Viewer3D viewer) {
		if (viewerMap != null && viewer!= null) {
			viewerMap.values().removeIf(viewer::equals);
			SNTUI ui = plugin.getUI();
			if (ui != null) {
				Viewer3D v = ui.getReconstructionViewer(false);
				if (v != null && v.getID() == viewer.getID()) {
					ui.setReconstructionViewer(null);
				}
			}
		}
	}
```

**Comment by tferr** [comment]
Great catch!
