### ISSUE TITLE
Java: How to initialize the SNT plugin programatically?

### ISSUE THREAD

**Issue by mcib3d** [morphonets/SNT#71]
Hi @tferr and @carshadi ,
Thanks for your help on the tracer class; now I am trying to use the SNT.autoTrace method but I am struggling on how to initialize SNT. I must admit, I am not familiar with the Fiji ecosystem as a developer. Here my small piece of code :

        SNTService service = new SNTService(); 
        service.setContext(new Context());
        service.initialize(imp,false);
        SNT snt = new SNT(new Context(), imp);
        return  snt.autoTrace(source, target, null, true);

When I run the plugin that will run the code, I get an error for the initialisation part : 

 
```
(Fiji Is Just) ImageJ 2.3.0/1.53f51; Java 1.8.0_172 [64-bit]; Linux 5.11.0-37-generic; 97MB of 1879MB (5%)
java.lang.NullPointerException
	at sc.fiji.snt.util.ImgUtils.getCtSlice(ImgUtils.java:245)
	at sc.fiji.snt.util.ImgUtils.getCtSlice3d(ImgUtils.java:222)
	at sc.fiji.snt.SNT.loadDatasetFromImagePlus(SNT.java:697)
	at sc.fiji.snt.SNT.initialize(SNT.java:642)
	at sc.fiji.snt.SNTService.initialize(SNTService.java:182)
	at mcib_plugins.AutoTrace2.traceWithoutPlugin(AutoTrace2.java:93)
	at mcib_plugins.AutoTrace2.getPath(AutoTrace2.java:60)
	at mcib_plugins.SpineJ_ROI.run(SpineJ_ROI.java:30)
	at ij.IJ.runUserPlugIn(IJ.java:241)
	at ij.IJ.runPlugIn(IJ.java:204)
	at ij.Executer.runCommand(Executer.java:150)
	at ij.Executer.run(Executer.java:68)
	at java.lang.Thread.run(Thread.java:748)
```
Thanks.

**Comment by mcib3d** [comment]
Hi @tferr  and @carshadi,

Thanks to your help it seems to work perfectly now, here is my small code for information : 
`
 Context context =  SNTUtils.getContext();
 SNTService sntService = context.getService(SNTService.class);
 SNT snt = sntService.initialize(imp, false);  // startUI
return snt.autoTrace(source, target, null, true);
`

**Comment by tferr** [comment]
Great. Glad it is working. Would  a `SNTService sntService =  SNTUtils.getSNTService();` convenience method make things more intuitive?
